### ISSUE TITLE
Color scheme on immersion_stats.py not distinct 

### ISSUE THREAD

**Issue by J-O-S-H-L** [friedrich-de/TMW_Bot#13]
The colors for the logging media types are too similar. I made them the same as the quiz roles but this was a mistake, sorry! Colors can be changes here:
https://github.com/friedrich-de/TMW_Bot/blob/36fb3bdfe8e9a4cd114b3cb418a13c380e0f0426/cogs/immersion_stats.py#L136-L144

**Comment by friedrich-de** [comment]
Looks good for me! Good work! #14
