### ISSUE TITLE
Media type barchart returns points when it should return ammount logged

### ISSUE THREAD

**Issue by J-O-S-H-L** [friedrich-de/TMW_Bot#16]
In this line of code:
https://github.com/friedrich-de/TMW_Bot/blob/b49104308dbf6fc976ff2889083a37e18e547c93/cogs/immersion_stats.py#L75
a vestigular function input was not cleaned up properly (by me). This mis-match of positional arguments means that immerison_type is always using the default value `None`. This makes the `process_bar_data` function follow the else path and show `points_received`instead of the desired  `ammount_logged`. 
### Example
 In this example image:
![image](https://github.com/user-attachments/assets/c926b8ea-5f3c-434d-bb40-cb927113d185)
the graph should show 2, 3, 3 episodes logged, but the points are showing

**Comment by friedrich-de** [comment]
Looks good, good work!
