### ISSUE TITLE
Adjustments to immersion_stats.py

### ISSUE THREAD

**Issue by friedrich-de** [friedrich-de/TMW_Bot#7]
Right now the /log_stats command only gives you an overview of earned points for all media types combined.

Suggestion:

Add media_type as an optional argument to the /log_stats command. A prepared list with Choice objects for this can be found in media_types.py in LOG_CHOICES. If a media_type is selected, instead of displaying the total points, the corresponding unit is used.

So  instead of `points_received` the `amount_logged` column is used. The unit name can be retrieved from MEDIA_TYPES in media_types.py.

**Comment by J-O-S-H-L** [comment]
Should have a solution today

**Comment by friedrich-de** [comment]
Good job!
